# Generated by Django 5.2.1 on 2025-06-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETLNodeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField()),
                ('node_id', models.CharField(max_length=64)),
                ('node_type', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=16)),
                ('message', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='etljob',
            name='transformation_rule',
            field=models.TextField(),
        ),
    ]
